### ISSUE TITLE
BDD 방식으로 테스트 코드 수정해보기

### ISSUE THREAD

**Issue by jeonghyeon-net** [surplus-developer/ll-goods#5]
테스트 코드를 좀 더 읽기 쉽게 만들어봅시다!
참고: https://www.popit.kr/bdd-behaviour-driven-development%EC%97%90-%EB%8C%80%ED%95%9C-%EA%B0%84%EB%9E%B5%ED%95%9C-%EC%A0%95%EB%A6%AC/

**Comment by gasd238** [comment]
이런 방식도 있군요. 참고해서 다음 테스트 코드 작성 때 참고 하겠습니다
